const BASE = "https://api.zingte.ai/v1";
const DOCS = "https://docs.zingte.ai";

export interface ApiSeedData {
  name: string;
  slug: string;
  description: string;
  category: string;
  baseUrl: string;
  priceMonthly: number;
  priceYearly: number;
  rateLimit: number;
  features: string[];
  documentation: string;
}

export const zingteApis: ApiSeedData[] = [
  {
    name: "LLM API",
    slug: "llm",
    description:
      "Enterprise-grade large language model API powering chatbots, copilots, customer support, internal knowledge assistants, and code generation. Supports system prompts, function calling, memory, and fine-tuned domain models.",
    category: "LLM & Conversational AI",
    baseUrl: `${BASE}/llm`,
    priceMonthly: 149.99,
    priceYearly: 1499.99,
    rateLimit: 10000,
    features: ["Multi-turn chat", "Streaming responses", "Function calling", "RAG embeddings"],
    documentation: `${DOCS}/llm`,
  },
  {
    name: "Image to Text API",
    slug: "image-to-text",
    description:
      "Converts images, scans, PDFs, and screenshots into structured text. Supports 120+ languages, layout preservation, table extraction, and scene understanding.",
    category: "Vision & OCR",
    baseUrl: `${BASE}/vision/ocr`,
    priceMonthly: 59.99,
    priceYearly: 599.99,
    rateLimit: 5000,
    features: ["OCR extraction", "Table & form parsing", "Handwriting recognition", "Batch processing"],
    documentation: `${DOCS}/vision/ocr`,
  },
  {
    name: "Text to Image API",
    slug: "text-to-image",
    description:
      "Generate photorealistic, illustrative, and branded visuals from text prompts with brand style presets, aspect ratios, and batch generation for marketing at scale.",
    category: "Generative AI",
    baseUrl: `${BASE}/gen/image`,
    priceMonthly: 79.99,
    priceYearly: 799.99,
    rateLimit: 2000,
    features: ["Prompt-to-image", "Inpaint & edit", "Style transfer", "4K upscaling"],
    documentation: `${DOCS}/gen/image`,
  },
  {
    name: "Text to Video API",
    slug: "text-to-video",
    description:
      "Transform written scripts, marketing copy, and product descriptions into polished video content with motion, transitions, voiceover sync, and brand templates.",
    category: "Generative AI",
    baseUrl: `${BASE}/gen/video/text`,
    priceMonthly: 129.99,
    priceYearly: 1299.99,
    rateLimit: 500,
    features: ["Text-to-video", "Storyboard mode", "Talking-head avatars", "Auto captions"],
    documentation: `${DOCS}/gen/video/text`,
  },
  {
    name: "Image to Video API",
    slug: "image-to-video",
    description:
      "Animate photographs, product images, portraits, and artwork. Ideal for e-commerce, social content, and personalized video messaging.",
    category: "Generative AI",
    baseUrl: `${BASE}/gen/video/image`,
    priceMonthly: 99.99,
    priceYearly: 999.99,
    rateLimit: 500,
    features: ["Image animation", "Morph transitions", "Product 360° spin", "Lip-sync"],
    documentation: `${DOCS}/gen/video/image`,
  },
  {
    name: "Lead Generation Automation API",
    slug: "lead-generation",
    description:
      "End-to-end lead generation pipeline: discover, enrich, score, verify, and route prospects into CRM and outreach workflows with AI-driven intent signals.",
    category: "Automation",
    baseUrl: `${BASE}/automation/leads`,
    priceMonthly: 89.99,
    priceYearly: 899.99,
    rateLimit: 3000,
    features: ["Prospect discovery", "Data enrichment", "Lead scoring", "Outreach sequences"],
    documentation: `${DOCS}/automation/leads`,
  },
  {
    name: "Contact Automation API",
    slug: "contact-automation",
    description:
      "Unified multi-channel communication engine with AI-powered personalization across email, WhatsApp, and SMS with compliance handling and two-way conversation management.",
    category: "Automation",
    baseUrl: `${BASE}/automation/contacts`,
    priceMonthly: 69.99,
    priceYearly: 699.99,
    rateLimit: 5000,
    features: ["Email campaigns", "WhatsApp Business", "SMS & MMS", "AI auto-reply"],
    documentation: `${DOCS}/automation/contacts`,
  },
  {
    name: "AI Dashboard API",
    slug: "ai-dashboard",
    description:
      "Embeddable AI-powered analytics dashboards with natural language queries, auto-generated insights, and real-time visualization of business and model performance metrics.",
    category: "Dashboard & Admin",
    baseUrl: `${BASE}/dashboard`,
    priceMonthly: 79.99,
    priceYearly: 799.99,
    rateLimit: 5000,
    features: ["Custom dashboards", "Real-time KPIs", "Threshold alerts", "Usage analytics"],
    documentation: `${DOCS}/dashboard`,
  },
  {
    name: "Dashboard Manager API",
    slug: "dashboard-manager",
    description:
      "Centralized administration layer for ISVs, agencies, and enterprises managing hundreds of client dashboards with RBAC, white-labeling, and template deployment.",
    category: "Dashboard & Admin",
    baseUrl: `${BASE}/dashboard/manager`,
    priceMonthly: 119.99,
    priceYearly: 1199.99,
    rateLimit: 3000,
    features: ["Multi-tenant admin", "User provisioning", "Template library", "Audit logs"],
    documentation: `${DOCS}/dashboard/manager`,
  },
  {
    name: "Word Correction API",
    slug: "word-correction",
    description:
      "Context-aware spelling, grammar, punctuation, and style correction supporting formal, casual, academic, and industry-specific writing modes.",
    category: "NLP & Language",
    baseUrl: `${BASE}/nlp/correct`,
    priceMonthly: 29.99,
    priceYearly: 299.99,
    rateLimit: 10000,
    features: ["Grammar correction", "Spelling fixes", "Style refinement", "Batch documents"],
    documentation: `${DOCS}/nlp/correct`,
  },
  {
    name: "Word Suggestion API",
    slug: "word-suggestion",
    description:
      "Predictive text, smart compose, and writing assistance that adapts to user style, document context, and industry vocabulary.",
    category: "NLP & Language",
    baseUrl: `${BASE}/nlp/suggest`,
    priceMonthly: 29.99,
    priceYearly: 299.99,
    rateLimit: 10000,
    features: ["Smart compose", "Next-word prediction", "Rewrite suggestions", "Snippet templates"],
    documentation: `${DOCS}/nlp/suggest`,
  },
  {
    name: "Dynamic Language Switch API",
    slug: "language-switch",
    description:
      "Seamlessly detect, switch, and maintain context across 200+ languages mid-conversation with RTL scripts, code-switching, and cultural adaptation.",
    category: "NLP & Language",
    baseUrl: `${BASE}/nlp/language`,
    priceMonthly: 49.99,
    priceYearly: 499.99,
    rateLimit: 8000,
    features: ["Auto language detect", "Live switching", "Locale adaptation", "200+ languages"],
    documentation: `${DOCS}/nlp/language`,
  },
  {
    name: "Workflow Automation API",
    slug: "workflow-automation",
    description:
      "No-code and API-driven workflow automation connecting Zingte AI models with CRMs, ERPs, databases, and third-party SaaS tools via triggers, conditions, and actions.",
    category: "Automation",
    baseUrl: `${BASE}/automation/workflows`,
    priceMonthly: 99.99,
    priceYearly: 999.99,
    rateLimit: 5000,
    features: ["Visual workflows", "Event triggers", "500+ connectors", "Execution monitoring"],
    documentation: `${DOCS}/automation/workflows`,
  },
  {
    name: "Agentic AI API",
    slug: "agentic-ai",
    description:
      "Autonomous AI agents that plan, use tools, browse data, call APIs, and complete multi-step business tasks with human-in-the-loop checkpoints and full audit trails.",
    category: "LLM & Conversational AI",
    baseUrl: `${BASE}/agents`,
    priceMonthly: 199.99,
    priceYearly: 1999.99,
    rateLimit: 2000,
    features: ["Autonomous agents", "Multi-agent orchestration", "Custom tools", "Full audit trace"],
    documentation: `${DOCS}/agents`,
  },
  {
    name: "Face Recognition API",
    slug: "face-recognition",
    description:
      "High-accuracy face detection, verification, and identification with support for masked faces, varying lighting, and large-scale identity galleries.",
    category: "Vision & OCR",
    baseUrl: `${BASE}/vision/face`,
    priceMonthly: 89.99,
    priceYearly: 899.99,
    rateLimit: 5000,
    features: ["Face detection", "1:1 verification", "1:N identification", "Attribute estimation"],
    documentation: `${DOCS}/vision/face`,
  },
  {
    name: "Liveness Detection API",
    slug: "liveness-detection",
    description:
      "Detect presentation attacks including printed photos, screen replays, masks, and deepfakes. Essential for secure remote identity verification and KYC compliance.",
    category: "Security & Safety",
    baseUrl: `${BASE}/vision/liveness`,
    priceMonthly: 99.99,
    priceYearly: 999.99,
    rateLimit: 3000,
    features: ["Passive liveness", "Active challenges", "Document matching", "Spoof risk scoring"],
    documentation: `${DOCS}/vision/liveness`,
  },
  {
    name: "Speech to Text API",
    slug: "speech-to-text",
    description:
      "Convert speech from audio files, live streams, phone calls, and video into accurate text. Supports 80+ languages, speaker diarization, and domain-specific vocabularies.",
    category: "Audio & Voice",
    baseUrl: `${BASE}/audio/stt`,
    priceMonthly: 59.99,
    priceYearly: 599.99,
    rateLimit: 5000,
    features: ["File transcription", "Real-time streaming", "Speaker diarization", "Batch processing"],
    documentation: `${DOCS}/audio/stt`,
  },
  {
    name: "Text to Speech API",
    slug: "text-to-speech",
    description:
      "Generate human-like speech from text with customizable voices, emotions, speaking rate, and brand-specific voice cloning for IVR, apps, and content production.",
    category: "Audio & Voice",
    baseUrl: `${BASE}/audio/tts`,
    priceMonthly: 49.99,
    priceYearly: 499.99,
    rateLimit: 8000,
    features: ["Natural synthesis", "Voice cloning", "SSML control", "100+ voices"],
    documentation: `${DOCS}/audio/tts`,
  },
  {
    name: "Sentiment Analysis API",
    slug: "sentiment-analysis",
    description:
      "Analyze text for positive, negative, and neutral sentiment plus granular emotions and aspect-level opinions for brand monitoring and support prioritization.",
    category: "NLP & Language",
    baseUrl: `${BASE}/nlp/sentiment`,
    priceMonthly: 39.99,
    priceYearly: 399.99,
    rateLimit: 10000,
    features: ["Sentiment scoring", "Aspect analysis", "Emotion detection", "Real-time monitoring"],
    documentation: `${DOCS}/nlp/sentiment`,
  },
  {
    name: "Document Intelligence API",
    slug: "document-intelligence",
    description:
      "Classify, extract, compare, and summarize structured and unstructured documents including invoices, contracts, resumes, forms, and regulatory filings.",
    category: "Vision & OCR",
    baseUrl: `${BASE}/docs`,
    priceMonthly: 79.99,
    priceYearly: 799.99,
    rateLimit: 3000,
    features: ["Document classification", "Field extraction", "Version comparison", "Compliance validation"],
    documentation: `${DOCS}/docs`,
  },
  {
    name: "Translation API",
    slug: "translation",
    description:
      "High-quality neural translation across 200+ language pairs with glossary support, document layout preservation, and industry-specific terminology.",
    category: "NLP & Language",
    baseUrl: `${BASE}/nlp/translate`,
    priceMonthly: 49.99,
    priceYearly: 499.99,
    rateLimit: 10000,
    features: ["Text translation", "Document translation", "Website localization", "Custom glossaries"],
    documentation: `${DOCS}/nlp/translate`,
  },
  {
    name: "Embedding & Semantic Search API",
    slug: "embedding-search",
    description:
      "Transform text into high-dimensional vectors for semantic search, duplicate detection, recommendation, and RAG-powered chatbots over private knowledge bases.",
    category: "Analytics & Intelligence",
    baseUrl: `${BASE}/embeddings`,
    priceMonthly: 69.99,
    priceYearly: 699.99,
    rateLimit: 8000,
    features: ["Vector embeddings", "Semantic search", "RAG queries", "Hybrid search"],
    documentation: `${DOCS}/embeddings`,
  },
  {
    name: "Content Moderation API",
    slug: "content-moderation",
    description:
      "Detect harmful, illegal, and policy-violating content across text, images, video, and audio with configurable thresholds for platforms and regulated industries.",
    category: "Security & Safety",
    baseUrl: `${BASE}/safety/moderate`,
    priceMonthly: 59.99,
    priceYearly: 599.99,
    rateLimit: 10000,
    features: ["Text moderation", "Image screening", "Video analysis", "Custom policy rules"],
    documentation: `${DOCS}/safety/moderate`,
  },
  {
    name: "Anomaly Detection API",
    slug: "anomaly-detection",
    description:
      "Identify unusual patterns in time-series data, transactions, sensor readings, and operational metrics with explainable AI alerts for fraud, failures, and disruptions.",
    category: "Analytics & Intelligence",
    baseUrl: `${BASE}/analytics/anomaly`,
    priceMonthly: 89.99,
    priceYearly: 899.99,
    rateLimit: 5000,
    features: ["Time-series detection", "Real-time scoring", "Alert configuration", "Root cause analysis"],
    documentation: `${DOCS}/analytics/anomaly`,
  },
  {
    name: "Recommendation Engine API",
    slug: "recommendation-engine",
    description:
      "AI-driven recommendation engine for products, content, users, and services using collaborative filtering, content-based signals, and real-time behavioral data.",
    category: "Analytics & Intelligence",
    baseUrl: `${BASE}/recommend`,
    priceMonthly: 79.99,
    priceYearly: 799.99,
    rateLimit: 8000,
    features: ["Product recommendations", "Content discovery", "Collaborative filtering", "Session personalization"],
    documentation: `${DOCS}/recommend`,
  },
  {
    name: "Predictive Analytics API",
    slug: "predictive-analytics",
    description:
      "Pre-trained predictive models for forecasting, scoring, and risk assessment for sales, operations, finance, and customer lifecycle management.",
    category: "Analytics & Intelligence",
    baseUrl: `${BASE}/analytics/predict`,
    priceMonthly: 99.99,
    priceYearly: 999.99,
    rateLimit: 5000,
    features: ["Demand forecasting", "Churn prediction", "Custom ML scoring", "What-if simulation"],
    documentation: `${DOCS}/analytics/predict`,
  },
  {
    name: "Speech to Speech API",
    slug: "speech-to-speech",
    description:
      "Convert spoken audio from one language to another in real time while preserving natural tone, pacing, and optionally the original speaker's voice identity.",
    category: "Audio & Voice",
    baseUrl: `${BASE}/audio/sts`,
    priceMonthly: 119.99,
    priceYearly: 1199.99,
    rateLimit: 3000,
    features: ["Real-time conversion", "Voice preservation", "Live call bridge", "Batch conversion"],
    documentation: `${DOCS}/audio/sts`,
  },
  {
    name: "AI Voice Over API",
    slug: "ai-voiceover",
    description:
      "Produce broadcast-quality AI voiceovers for ads, explainers, e-learning, documentaries, and product demos with emotion control and multi-language dubbing.",
    category: "Audio & Voice",
    baseUrl: `${BASE}/audio/voiceover`,
    priceMonthly: 69.99,
    priceYearly: 699.99,
    rateLimit: 3000,
    features: ["Script voiceover", "Video dubbing", "Multi-language output", "Brand voice profiles"],
    documentation: `${DOCS}/audio/voiceover`,
  },
  {
    name: "AI Cold Calling Agent API",
    slug: "cold-calling-agent",
    description:
      "AI-powered outbound calling agent that dials prospects, delivers personalized pitches, handles objections, qualifies leads, and transfers hot leads to human sales reps.",
    category: "Automation",
    baseUrl: `${BASE}/automation/voice/cold-call`,
    priceMonthly: 179.99,
    priceYearly: 1799.99,
    rateLimit: 1000,
    features: ["Outbound campaigns", "Lead qualification", "Objection handling", "CRM handoff"],
    documentation: `${DOCS}/automation/voice/cold-call`,
  },
  {
    name: "Social Media Automation API",
    slug: "social-media-automation",
    description:
      "Automate social media publishing, content generation, engagement replies, and performance reporting across Instagram, Facebook, LinkedIn, Twitter/X, TikTok, and YouTube.",
    category: "Automation",
    baseUrl: `${BASE}/automation/social`,
    priceMonthly: 59.99,
    priceYearly: 599.99,
    rateLimit: 5000,
    features: ["Multi-platform posting", "AI content generation", "Auto-reply to DMs", "Engagement analytics"],
    documentation: `${DOCS}/automation/social`,
  },
  {
    name: "CRM Pipeline Automation API",
    slug: "crm-pipeline-automation",
    description:
      "Automate CRM hygiene, deal stage progression, follow-up reminders, contact enrichment, and lead scoring across Salesforce, HubSpot, Zoho, and Pipedrive.",
    category: "Automation",
    baseUrl: `${BASE}/automation/crm`,
    priceMonthly: 89.99,
    priceYearly: 899.99,
    rateLimit: 5000,
    features: ["Bi-directional CRM sync", "Deal stage automation", "Lead enrichment", "Activity scoring"],
    documentation: `${DOCS}/automation/crm`,
  },
  {
    name: "Appointment Automation API",
    slug: "appointment-automation",
    description:
      "End-to-end appointment automation: availability checking, booking, rescheduling, cancellation handling, waitlist management, and multi-channel reminders.",
    category: "Automation",
    baseUrl: `${BASE}/automation/scheduling`,
    priceMonthly: 49.99,
    priceYearly: 499.99,
    rateLimit: 5000,
    features: ["Online booking", "Calendar sync", "SMS reminders", "Waitlist management"],
    documentation: `${DOCS}/automation/scheduling`,
  },
  {
    name: "Invoice & Billing Automation API",
    slug: "invoice-billing-automation",
    description:
      "Automate invoice generation, payment reminders, overdue collections, subscription renewals, and payment reconciliation with Stripe, PayPal, QuickBooks, and Xero integrations.",
    category: "Automation",
    baseUrl: `${BASE}/automation/billing`,
    priceMonthly: 69.99,
    priceYearly: 699.99,
    rateLimit: 3000,
    features: ["Auto invoicing", "Payment reminders", "Dunning flows", "Subscription billing"],
    documentation: `${DOCS}/automation/billing`,
  },
  {
    name: "Report Generation Automation API",
    slug: "report-generation-automation",
    description:
      "Automatically pull data from APIs and databases, generate formatted PDF, Excel, and HTML reports with AI-written narrative summaries, and deliver on schedule.",
    category: "Automation",
    baseUrl: `${BASE}/automation/reports`,
    priceMonthly: 59.99,
    priceYearly: 599.99,
    rateLimit: 2000,
    features: ["Scheduled reports", "AI executive summaries", "PDF & Excel export", "Multi-channel delivery"],
    documentation: `${DOCS}/automation/reports`,
  },
  {
    name: "Data Sync Automation API",
    slug: "data-sync-automation",
    description:
      "Keep data synchronized across CRM, ERP, e-commerce, marketing, support, and custom databases with configurable field mapping, transformation rules, and scheduled sync.",
    category: "Automation",
    baseUrl: `${BASE}/automation/sync`,
    priceMonthly: 79.99,
    priceYearly: 799.99,
    rateLimit: 5000,
    features: ["Cross-app pipelines", "Field mapping", "Scheduled sync", "Error monitoring"],
    documentation: `${DOCS}/automation/sync`,
  },
];
